### ISSUE TITLE
Use blog posts in the Rust wiki

### ISSUE THREAD

**Issue by Aloso** [pretzelhammer/rust-blog#6]
According to the readme, the license applies to the code examples, but not whole blog posts, so I have to ask:

Am I allowed to copy your blog post from 2020-05-19 to the [Rust wiki](https://runrust.miraheze.org) and quote you as the source?

**Comment by pretzelhammer** [comment]
I don't want my blog posts to be copied & pasted to different places around the internet since I might make improvements & updates to my blog posts in the future and the copies will become stale since there will be no one to maintain them. If you want to include one of my blog posts in that wiki it would be better to just link directly to the blog post.

I would be okay with someone copying my blog posts if they also added significant value to the post, like translating it to another language, which is not something I'm able to do as I only speak and write English.
