### ISSUE TITLE
Struct methods can also NOT have elided lifetimes right?

### ISSUE THREAD

**Issue by davidatsurge** [pretzelhammer/rust-blog#62]
The list of common misconceptions contains:

>  if you've ever written a struct method ... then your code has generic elided lifetime annotations all over it.

But that's not always true right?

```rust
struct A {}
impl A {
    fn method(self) -> A {
        self
    }
}
pub fn main() {
	let a = A {};
	a.method();

}
```

**Comment by pretzelhammer** [comment]
yeah, you're right.

be careful about making assumptions about methods which take/return `self` tho, because `self` could contain refs, and those refs lifetimes would be elided, e.g.

```rust
struct Struct<'a> {
    s: &'a str,
}

impl Struct<'_> {
    fn method(self) -> Self {
        self
    }
}
```

desugars to:

```rust
struct Struct<'a> {
    s: &'a str,
}

impl<'a> Struct<'a> {
    fn method(self: Struct<'a>) -> Struct<'a> {
        self
    }
}
```

but anyway, i updated the wording in the article [in this commit](https://github.com/pretzelhammer/rust-blog/commit/1d590c9cd18e431641d1dd219096868d12500fa9), thanks for making this issue
