### ISSUE TITLE
Clarify a license for blog posts themselves

### ISSUE THREAD

**Issue by AnthonyMikh** [pretzelhammer/rust-blog#9]
Quite self-explanatory title. I want to translate one of your blog posts and publish it on a IT platform, namely habr.com, however, I am not sure if I am allowed to do so. Here are the relevant parts of [Habr user agreement](https://account.habr.com/info/agreement/?hl=en_US) at the moment (emphasis mine):

> **4\.8.** By accepting the terms and conditions of this Agreement, the User shall provide Habr with a free (non-exclusive) license for using the Content in the following ways:
>
> <...>
> * to distribute copies of the Content, i.e. to provide access to material reproduced in any material form, including through network and otherwise, as well as by **selling, renting, leasing, lending**, including importation for any of these purposes (right of distribution);
>
> <...>
> * right to assign all or part of the received rights **to third parties** (the right to sublicense).
> 
> <...>
> **4\.11.** The User **guarantees the right** to use the Content under the terms and conditions of the aforementioned license to the extend required.

Since you didn't specify a license for posts themselves, you [still have the exclusive rights](https://docs.github.com/en/github/site-policy/github-terms-of-service#d-user-generated-content) for all your content, thereby I can't even legally publish a translation, not only on Habr but anywhere.

**Comment by pretzelhammer** [comment]
I [left a comment here](https://github.com/pretzelhammer/rust-blog/issues/6#issuecomment-641429392) about my stance on translations but you've probably already read that. Hmmm, to be more precise: I'd like to retain exclusive rights to the original English-version of my blog posts but if you translate my blog post to another language you can treat the translation as if it was MIT or Apache 2 licensed. Does that work / make sense? If so, I can add it to my blog's main readme.md

Also, although I don't plan to enforce this, I would appreciate it if in your translation you linked to the original English source material somewhere to give attribution. And once the translation is published please consider opening an issue on this repo to notify me because I'd like to somehow list the translations next to the blog posts in case someone would prefer to read some non-English version.

**Comment by AnthonyMikh** [comment]
> Hmmm, to be more precise: I'd like to retain exclusive rights to the original English-version of my blog posts but if you translate my blog post to another language you can treat the translation as if it was MIT or Apache 2 licensed. Does that work / make sense? If so, I can add it to my blog's main readme.md

I does probably, however, since I am not a lawyer, I can't say for sure. Nevertheless, thanks, for outlining borders.

> Also, although I don't plan to enforce this, I would appreciate it if in your translation you linked to the original English source material somewhere to give attribution. And once the translation is published please consider opening an issue on this repo to notify me because I'd like to somehow list the translations next to the blog posts in case someone would prefer to read some non-English version.

Okay, no problem.

**Comment by pretzelhammer** [comment]
I've updated the readme to be more clear/explicit regarding my stance on translations, so I'm going to close this issue now.
