### ISSUE TITLE
Could you create post in your blog about my book?

### ISSUE THREAD

**Issue by evgenyigumnov** [pretzelhammer/rust-blog#91]
# Rust Recipes for Beginners
## A book for beginners in Rust, not beginners in programming

Who is this book for?

This book is intended for those who are new to the Rust programming language but not to programming in general. In other words, it is designed for programmers who already have experience in other languages and want to learn Rust. Overall, Rust is not the best choice as a first programming language for beginners. It's recommended to start with simpler languages like Python or TypeScript, then progress to languages such as Java or Go, and only after gaining a solid foundation, approach more complex languages like C/C++ or Rust.

https://github.com/evgenyigumnov/rust-recipes-for-beginners

**Comment by lebensterben** [comment]
> Idea and Concept of the Book:
>
> The essence of this book is that it is created with the help of Large Language Models (LLMs). The author formulates the requirements for each section, and the LLM generates the text and code examples. The author then edits and verifies the code through compilation and test execution. 

feels cheap

**Comment by pretzelhammer** [comment]
I recently published a blog post called [Learning Rust in 2024](https://github.com/pretzelhammer/rust-blog/blob/master/posts/learning-rust-in-2024.md) where I recommend learning resources for beginners.

The resources I recommend in the post were curated given this criteria:
1. It's a complete work.
2. It has some form of social-proof:
    a. It's popular within the Rust community, or
    b. It's not popular _yet_ but was developed by an experienced and reputable Rustacean.
3. I personally used the resource and thought it was well-made.

Your book fails to meet criteria 1 because it's incomplete. After that criteria has been met please submit your book to various online Rust communities and newsletters to try to get eyes on it. If you can get at least 500 stars on your Github repo I'd consider criteria 2 to be met. After criteria 1 & 2 are met I'll go through the book myself and if it passes my personal bar for quality then I may consider adding it as an [Honorable Mention](https://github.com/pretzelhammer/rust-blog/blob/master/posts/learning-rust-in-2024.md#honorable-mentions) to [Learning Rust in 2024](https://github.com/pretzelhammer/rust-blog/blob/master/posts/learning-rust-in-2024.md) .

I'm closing this issue for now, but feel free to re-open it once criteria 1 & 2 are met to let me know that I should go through and review your book myself.
